

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class Bioscoop : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Bioscoop entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Bioscoop()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Bioscoop(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Bioscoop> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Bioscoop.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bioscoop_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bioscoop_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int BioscoopId
        {
            get
            {
                return global::LightSwitchApplication.Bioscoop.DetailsClass.GetValue(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.BioscoopId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BioscoopId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BioscoopId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BioscoopId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Naam
        {
            get
            {
                return global::LightSwitchApplication.Bioscoop.DetailsClass.GetValue(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Naam);
            }
            set
            {
                global::LightSwitchApplication.Bioscoop.DetailsClass.SetValue(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Naam, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Naam_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Naam_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Naam_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Stad
        {
            get
            {
                return global::LightSwitchApplication.Bioscoop.DetailsClass.GetValue(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Stad);
            }
            set
            {
                global::LightSwitchApplication.Bioscoop.DetailsClass.SetValue(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Stad, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Stad_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Stad_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Stad_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Email
        {
            get
            {
                return global::LightSwitchApplication.Bioscoop.DetailsClass.GetValue(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Email);
            }
            set
            {
                global::LightSwitchApplication.Bioscoop.DetailsClass.SetValue(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Email, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Telefoon
        {
            get
            {
                return global::LightSwitchApplication.Bioscoop.DetailsClass.GetValue(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Telefoon);
            }
            set
            {
                global::LightSwitchApplication.Bioscoop.DetailsClass.SetValue(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Telefoon, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefoon_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefoon_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefoon_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Zaal> Zaals
        {
            get
            {
                return global::LightSwitchApplication.Bioscoop.DetailsClass.GetValue(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Zaals);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Zaal> ZaalsQuery
        {
            get
            {
                return global::LightSwitchApplication.Bioscoop.DetailsClass.GetQuery(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Zaals);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.BioscoopReview> BioscoopReviews
        {
            get
            {
                return global::LightSwitchApplication.Bioscoop.DetailsClass.GetValue(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.BioscoopReviews);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.BioscoopReview> BioscoopReviewsQuery
        {
            get
            {
                return global::LightSwitchApplication.Bioscoop.DetailsClass.GetQuery(this, global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.BioscoopReviews);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Bioscoop,
                global::LightSwitchApplication.Bioscoop.DetailsClass,
                global::LightSwitchApplication.Bioscoop.DetailsClass.IImplementation,
                global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.BioscoopId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass>.Entry
                __BioscoopEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass>.Entry(
                    global::LightSwitchApplication.Bioscoop.DetailsClass.__Bioscoop_CreateNew,
                    global::LightSwitchApplication.Bioscoop.DetailsClass.__Bioscoop_Created,
                    global::LightSwitchApplication.Bioscoop.DetailsClass.__Bioscoop_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Bioscoop __Bioscoop_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Bioscoop> es)
            {
                return new global::LightSwitchApplication.Bioscoop(es);
            }
            private static void __Bioscoop_Created(global::LightSwitchApplication.Bioscoop e)
            {
                e.Bioscoop_Created();
            }
            private static bool __Bioscoop_AllowSaveWithErrors(global::LightSwitchApplication.Bioscoop e)
            {
                bool result = false;
                e.Bioscoop_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, int> BioscoopId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.BioscoopId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string> Naam
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Naam) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string> Stad
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Stad) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string> Email
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Email) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string> Telefoon
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Telefoon) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.Zaal> Zaals
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Zaals) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.Zaal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.BioscoopReview> BioscoopReviews
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.BioscoopReviews) as global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.BioscoopReview>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int BioscoopId { get; }
                new string Naam { get; set; }
                new string Stad { get; set; }
                new string Email { get; set; }
                new string Telefoon { get; set; }
                new global::System.Collections.IEnumerable Zaals { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, int>.Entry
                    BioscoopId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, int>.Entry(
                        "BioscoopId",
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._BioscoopId_Stub,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._BioscoopId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._BioscoopId_Validate,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._BioscoopId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._BioscoopId_OnValueChanged);
                private static void _BioscoopId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bioscoop.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, int>.Data> c, global::LightSwitchApplication.Bioscoop.DetailsClass d, object sf)
                {
                    c(d, ref d._BioscoopId, sf);
                }
                private static bool _BioscoopId_ComputeIsReadOnly(global::LightSwitchApplication.Bioscoop e)
                {
                    bool result = false;
                    e.BioscoopId_IsReadOnly(ref result);
                    return result;
                }
                private static void _BioscoopId_Validate(global::LightSwitchApplication.Bioscoop e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.BioscoopId_Validate(r);
                }
                private static int _BioscoopId_GetImplementationValue(global::LightSwitchApplication.Bioscoop.DetailsClass d)
                {
                    return d.ImplementationEntity.BioscoopId;
                }
                private static void _BioscoopId_OnValueChanged(global::LightSwitchApplication.Bioscoop e)
                {
                    e.BioscoopId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Entry
                    Naam = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Entry(
                        "Naam",
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Naam_Stub,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Naam_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Naam_Validate,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Naam_GetImplementationValue,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Naam_SetImplementationValue,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Naam_OnValueChanged);
                private static void _Naam_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bioscoop.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Data> c, global::LightSwitchApplication.Bioscoop.DetailsClass d, object sf)
                {
                    c(d, ref d._Naam, sf);
                }
                private static bool _Naam_ComputeIsReadOnly(global::LightSwitchApplication.Bioscoop e)
                {
                    bool result = false;
                    e.Naam_IsReadOnly(ref result);
                    return result;
                }
                private static void _Naam_Validate(global::LightSwitchApplication.Bioscoop e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Naam_Validate(r);
                }
                private static string _Naam_GetImplementationValue(global::LightSwitchApplication.Bioscoop.DetailsClass d)
                {
                    return d.ImplementationEntity.Naam;
                }
                private static void _Naam_SetImplementationValue(global::LightSwitchApplication.Bioscoop.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Naam = v;
                }
                private static void _Naam_OnValueChanged(global::LightSwitchApplication.Bioscoop e)
                {
                    e.Naam_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Entry
                    Stad = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Entry(
                        "Stad",
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Stad_Stub,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Stad_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Stad_Validate,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Stad_GetImplementationValue,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Stad_SetImplementationValue,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Stad_OnValueChanged);
                private static void _Stad_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bioscoop.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Data> c, global::LightSwitchApplication.Bioscoop.DetailsClass d, object sf)
                {
                    c(d, ref d._Stad, sf);
                }
                private static bool _Stad_ComputeIsReadOnly(global::LightSwitchApplication.Bioscoop e)
                {
                    bool result = false;
                    e.Stad_IsReadOnly(ref result);
                    return result;
                }
                private static void _Stad_Validate(global::LightSwitchApplication.Bioscoop e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Stad_Validate(r);
                }
                private static string _Stad_GetImplementationValue(global::LightSwitchApplication.Bioscoop.DetailsClass d)
                {
                    return d.ImplementationEntity.Stad;
                }
                private static void _Stad_SetImplementationValue(global::LightSwitchApplication.Bioscoop.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Stad = v;
                }
                private static void _Stad_OnValueChanged(global::LightSwitchApplication.Bioscoop e)
                {
                    e.Stad_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Entry
                    Email = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Entry(
                        "Email",
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Email_Stub,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Email_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Email_Validate,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Email_GetImplementationValue,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Email_SetImplementationValue,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Email_OnValueChanged);
                private static void _Email_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bioscoop.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Data> c, global::LightSwitchApplication.Bioscoop.DetailsClass d, object sf)
                {
                    c(d, ref d._Email, sf);
                }
                private static bool _Email_ComputeIsReadOnly(global::LightSwitchApplication.Bioscoop e)
                {
                    bool result = false;
                    e.Email_IsReadOnly(ref result);
                    return result;
                }
                private static void _Email_Validate(global::LightSwitchApplication.Bioscoop e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Email_Validate(r);
                }
                private static string _Email_GetImplementationValue(global::LightSwitchApplication.Bioscoop.DetailsClass d)
                {
                    return d.ImplementationEntity.Email;
                }
                private static void _Email_SetImplementationValue(global::LightSwitchApplication.Bioscoop.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Email = v;
                }
                private static void _Email_OnValueChanged(global::LightSwitchApplication.Bioscoop e)
                {
                    e.Email_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Entry
                    Telefoon = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Entry(
                        "Telefoon",
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Telefoon_Stub,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Telefoon_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Telefoon_Validate,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Telefoon_GetImplementationValue,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Telefoon_SetImplementationValue,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Telefoon_OnValueChanged);
                private static void _Telefoon_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bioscoop.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Data> c, global::LightSwitchApplication.Bioscoop.DetailsClass d, object sf)
                {
                    c(d, ref d._Telefoon, sf);
                }
                private static bool _Telefoon_ComputeIsReadOnly(global::LightSwitchApplication.Bioscoop e)
                {
                    bool result = false;
                    e.Telefoon_IsReadOnly(ref result);
                    return result;
                }
                private static void _Telefoon_Validate(global::LightSwitchApplication.Bioscoop e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Telefoon_Validate(r);
                }
                private static string _Telefoon_GetImplementationValue(global::LightSwitchApplication.Bioscoop.DetailsClass d)
                {
                    return d.ImplementationEntity.Telefoon;
                }
                private static void _Telefoon_SetImplementationValue(global::LightSwitchApplication.Bioscoop.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Telefoon = v;
                }
                private static void _Telefoon_OnValueChanged(global::LightSwitchApplication.Bioscoop e)
                {
                    e.Telefoon_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.Zaal>.Entry
                    Zaals = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.Zaal>.Entry(
                        "Zaals",
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Zaals_Stub,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Zaals_GetReferencedEntities,
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._Zaals_GetEntityCollection);
                private static void _Zaals_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bioscoop.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.Zaal>.Data> c, global::LightSwitchApplication.Bioscoop.DetailsClass d, object sf)
                {
                    c(d, ref d._Zaals, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Zaal> _Zaals_GetReferencedEntities(global::LightSwitchApplication.Bioscoop.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Zaal, global::LightSwitchApplication.Zaal.DetailsClass>(global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties.Zaals, ref d._Zaals);
                }
                private static global::System.Collections.IEnumerable _Zaals_GetEntityCollection(global::LightSwitchApplication.Bioscoop.DetailsClass d)
                {
                    return d.ImplementationEntity.Zaals;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.BioscoopReview>.Entry
                    BioscoopReviews = new global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.BioscoopReview>.Entry(
                        "BioscoopReviews",
                        global::LightSwitchApplication.Bioscoop.DetailsClass.PropertySetProperties._BioscoopReviews_Stub);
                private static void _BioscoopReviews_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bioscoop.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.BioscoopReview>.Data> c, global::LightSwitchApplication.Bioscoop.DetailsClass d, object sf)
                {
                    c(d, ref d._BioscoopReviews, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, int>.Data _BioscoopId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Data _Naam;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Data _Stad;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Data _Email;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, string>.Data _Telefoon;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.Zaal>.Data _Zaals;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Bioscoop, global::LightSwitchApplication.Bioscoop.DetailsClass, global::LightSwitchApplication.BioscoopReview>.Data _BioscoopReviews;
            
        }
    
        #endregion
    }
    
    #endregion
}
