//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 7-4-2016 19:28:05
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for ApplicationData in the schema.
    /// </summary>
    public partial class ApplicationData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for DierenartsSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Dierenarts> DierenartsSet
        {
            get
            {
                if ((this._DierenartsSet == null))
                {
                    this._DierenartsSet = base.CreateQuery<Dierenarts>("DierenartsSet");
                }
                return this._DierenartsSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Dierenarts> _DierenartsSet;
        /// <summary>
        /// There are no comments for Diers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Dier> Diers
        {
            get
            {
                if ((this._Diers == null))
                {
                    this._Diers = base.CreateQuery<Dier>("Diers");
                }
                return this._Diers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Dier> _Diers;
        /// <summary>
        /// There are no comments for Eigenaars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Eigenaar> Eigenaars
        {
            get
            {
                if ((this._Eigenaars == null))
                {
                    this._Eigenaars = base.CreateQuery<Eigenaar>("Eigenaars");
                }
                return this._Eigenaars;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Eigenaar> _Eigenaars;
        /// <summary>
        /// There are no comments for Behandelings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Behandeling> Behandelings
        {
            get
            {
                if ((this._Behandelings == null))
                {
                    this._Behandelings = base.CreateQuery<Behandeling>("Behandelings");
                }
                return this._Behandelings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Behandeling> _Behandelings;
        /// <summary>
        /// There are no comments for DierenartsSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDierenartsSet(Dierenarts dierenarts)
        {
            base.AddObject("DierenartsSet", dierenarts);
        }
        /// <summary>
        /// There are no comments for Diers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDiers(Dier dier)
        {
            base.AddObject("Diers", dier);
        }
        /// <summary>
        /// There are no comments for Eigenaars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEigenaars(Eigenaar eigenaar)
        {
            base.AddObject("Eigenaars", eigenaar);
        }
        /// <summary>
        /// There are no comments for Behandelings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBehandelings(Behandeling behandeling)
        {
            base.AddObject("Behandelings", behandeling);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"Dierenarts\"><Key><PropertyRef Name=\"Id\" /></Ke" +
                "y><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGenerate" +
                "dPattern=\"Identity\" /><Property Name=\"Voornaam\" Type=\"Edm.String\" Nullable=\"fals" +
                "e\" MaxLength=\"255\" /><Property Name=\"Achternaam\" Type=\"Edm.String\" Nullable=\"fal" +
                "se\" MaxLength=\"255\" /><Property Name=\"Telefoonnummer\" Type=\"Edm.String\" Nullable" +
                "=\"false\" MaxLength=\"255\" /><Property Name=\"Emailadres\" Type=\"Edm.String\" Nullabl" +
                "e=\"false\" MaxLength=\"255\" /><Property Name=\"Salaris\" Type=\"Edm.Decimal\" Nullable" +
                "=\"false\" Precision=\"18\" Scale=\"2\" /><Property Name=\"CreatedBy\" Type=\"Edm.String\"" +
                " MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Propert" +
                "y Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Modified" +
                "\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Null" +
                "able=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed\"" +
                " /><NavigationProperty Name=\"Behandelings\" Relationship=\"LightSwitchApplication." +
                "Behandeling_Dierenarts\" ToRole=\"Behandeling\" FromRole=\"Dierenarts\" /></EntityTyp" +
                "e><EntityType Name=\"Dier\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id" +
                "\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identity\" " +
                "/><Property Name=\"Naam\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Pr" +
                "operty Name=\"Soort\" Type=\"Edm.String\" MaxLength=\"2\" /><Property Name=\"Gewicht\" T" +
                "ype=\"Edm.Decimal\" Nullable=\"false\" Precision=\"18\" Scale=\"2\" /><Property Name=\"Ra" +
                "s\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=\"Geslacht" +
                "\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Geboortedatum\" Type=\"Edm.D" +
                "ateTime\" /><Property Name=\"Dier_Eigenaar\" Type=\"Edm.Int32\" Nullable=\"false\" /><P" +
                "roperty Name=\"CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Cre" +
                "ated\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" " +
                "MaxLength=\"255\" /><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Propert" +
                "y Name=\"RowVersion\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" a" +
                "nnotation:StoreGeneratedPattern=\"Computed\" /><NavigationProperty Name=\"Behandeli" +
                "ngs\" Relationship=\"LightSwitchApplication.Behandeling_Dier\" ToRole=\"Behandeling\"" +
                " FromRole=\"Dier\" /><NavigationProperty Name=\"Eigenaar\" Relationship=\"LightSwitch" +
                "Application.Dier_Eigenaar\" ToRole=\"Eigenaar\" FromRole=\"Dier\" /></EntityType><Ent" +
                "ityType Name=\"Eigenaar\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" " +
                "Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identity\" />" +
                "<Property Name=\"Naam\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Prop" +
                "erty Name=\"Adres\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property" +
                " Name=\"Postcode\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property " +
                "Name=\"Woonplaats\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" /><Property" +
                " Name=\"CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" T" +
                "ype=\"Edm.DateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLeng" +
                "th=\"255\" /><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=" +
                "\"RowVersion\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotati" +
                "on:StoreGeneratedPattern=\"Computed\" /><NavigationProperty Name=\"Diers\" Relations" +
                "hip=\"LightSwitchApplication.Dier_Eigenaar\" ToRole=\"Dier\" FromRole=\"Eigenaar\" /><" +
                "/EntityType><EntityType Name=\"Behandeling\"><Key><PropertyRef Name=\"Id\" /></Key><" +
                "Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPa" +
                "ttern=\"Identity\" /><Property Name=\"Omschrijving\" Type=\"Edm.String\" Nullable=\"fal" +
                "se\" MaxLength=\"255\" /><Property Name=\"Behandeldatum\" Type=\"Edm.DateTime\" Nullabl" +
                "e=\"false\" /><Property Name=\"Bedrag\" Type=\"Edm.Decimal\" Nullable=\"false\" Precisio" +
                "n=\"18\" Scale=\"2\" /><Property Name=\"Behandeling_Dier\" Type=\"Edm.Int32\" Nullable=\"" +
                "false\" /><Property Name=\"Behandeling_Dierenarts\" Type=\"Edm.Int32\" Nullable=\"fals" +
                "e\" /><Property Name=\"CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Na" +
                "me=\"Created\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.S" +
                "tring\" MaxLength=\"255\" /><Property Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><" +
                "Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"F" +
                "ixed\" annotation:StoreGeneratedPattern=\"Computed\" /><NavigationProperty Name=\"Di" +
                "er\" Relationship=\"LightSwitchApplication.Behandeling_Dier\" ToRole=\"Dier\" FromRol" +
                "e=\"Behandeling\" /><NavigationProperty Name=\"Dierenarts\" Relationship=\"LightSwitc" +
                "hApplication.Behandeling_Dierenarts\" ToRole=\"Dierenarts\" FromRole=\"Behandeling\" " +
                "/></EntityType><Association Name=\"Behandeling_Dier\"><End Role=\"Dier\" Type=\"Light" +
                "SwitchApplication.Dier\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End" +
                " Role=\"Behandeling\" Type=\"LightSwitchApplication.Behandeling\" Multiplicity=\"*\" /" +
                "><ReferentialConstraint><Principal Role=\"Dier\"><PropertyRef Name=\"Id\" /></Princi" +
                "pal><Dependent Role=\"Behandeling\"><PropertyRef Name=\"Behandeling_Dier\" /></Depen" +
                "dent></ReferentialConstraint></Association><Association Name=\"Behandeling_Dieren" +
                "arts\"><End Role=\"Dierenarts\" Type=\"LightSwitchApplication.Dierenarts\" Multiplici" +
                "ty=\"1\" /><End Role=\"Behandeling\" Type=\"LightSwitchApplication.Behandeling\" Multi" +
                "plicity=\"*\" /><ReferentialConstraint><Principal Role=\"Dierenarts\"><PropertyRef N" +
                "ame=\"Id\" /></Principal><Dependent Role=\"Behandeling\"><PropertyRef Name=\"Behandel" +
                "ing_Dierenarts\" /></Dependent></ReferentialConstraint></Association><Association" +
                " Name=\"Dier_Eigenaar\"><End Role=\"Eigenaar\" Type=\"LightSwitchApplication.Eigenaar" +
                "\" Multiplicity=\"1\" /><End Role=\"Dier\" Type=\"LightSwitchApplication.Dier\" Multipl" +
                "icity=\"*\" /><ReferentialConstraint><Principal Role=\"Eigenaar\"><PropertyRef Name=" +
                "\"Id\" /></Principal><Dependent Role=\"Dier\"><PropertyRef Name=\"Dier_Eigenaar\" /></" +
                "Dependent></ReferentialConstraint></Association><EntityContainer Name=\"Applicati" +
                "onData\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"DierenartsSet\" Entity" +
                "Type=\"LightSwitchApplication.Dierenarts\" /><EntitySet Name=\"Diers\" EntityType=\"L" +
                "ightSwitchApplication.Dier\" /><EntitySet Name=\"Eigenaars\" EntityType=\"LightSwitc" +
                "hApplication.Eigenaar\" /><EntitySet Name=\"Behandelings\" EntityType=\"LightSwitchA" +
                "pplication.Behandeling\" /><AssociationSet Name=\"Behandeling_Dier\" Association=\"L" +
                "ightSwitchApplication.Behandeling_Dier\"><End Role=\"Dier\" EntitySet=\"Diers\" /><En" +
                "d Role=\"Behandeling\" EntitySet=\"Behandelings\" /></AssociationSet><AssociationSet" +
                " Name=\"Behandeling_Dierenarts\" Association=\"LightSwitchApplication.Behandeling_D" +
                "ierenarts\"><End Role=\"Dierenarts\" EntitySet=\"DierenartsSet\" /><End Role=\"Behande" +
                "ling\" EntitySet=\"Behandelings\" /></AssociationSet><AssociationSet Name=\"Dier_Eig" +
                "enaar\" Association=\"LightSwitchApplication.Dier_Eigenaar\"><End Role=\"Eigenaar\" E" +
                "ntitySet=\"Eigenaars\" /><End Role=\"Dier\" EntitySet=\"Diers\" /></AssociationSet><Fu" +
                "nctionImport Name=\"EigenarenUitBreda\" ReturnType=\"Collection(LightSwitchApplicat" +
                "ion.Eigenaar)\" EntitySet=\"Eigenaars\" m:HttpMethod=\"GET\" /><FunctionImport Name=\"" +
                "EigenarenOpInput\" ReturnType=\"Collection(LightSwitchApplication.Eigenaar)\" Entit" +
                "ySet=\"Eigenaars\" m:HttpMethod=\"GET\"><Parameter Name=\"Woonpl";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = @"aats"" Type=""Edm.String"" Mode=""In"" /></FunctionImport><FunctionImport Name=""AlleKattenEnHonden"" ReturnType=""Collection(LightSwitchApplication.Dier)"" EntitySet=""Diers"" m:HttpMethod=""GET"" /><FunctionImport Name=""MeerDanTienDieren"" ReturnType=""Collection(LightSwitchApplication.Dierenarts)"" EntitySet=""DierenartsSet"" m:HttpMethod=""GET"" /><FunctionImport Name=""DierenartsenBijAantalBehandelingenInput"" ReturnType=""Collection(LightSwitchApplication.Dierenarts)"" EntitySet=""DierenartsSet"" m:HttpMethod=""GET""><Parameter Name=""AantalBehandelingenParameter"" Type=""Edm.Int32"" Mode=""In"" /></FunctionImport><FunctionImport Name=""Microsoft_LightSwitch_GetCanInformation"" ReturnType=""Edm.String"" m:HttpMethod=""GET""><Parameter Name=""dataServiceMembers"" Type=""Edm.String"" Mode=""In"" /></FunctionImport></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Dierenarts in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DierenartsSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Dierenarts : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Dierenarts object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="voornaam">Initial value of Voornaam.</param>
        /// <param name="achternaam">Initial value of Achternaam.</param>
        /// <param name="telefoonnummer">Initial value of Telefoonnummer.</param>
        /// <param name="emailadres">Initial value of Emailadres.</param>
        /// <param name="salaris">Initial value of Salaris.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Dierenarts CreateDierenarts(int ID, string voornaam, string achternaam, string telefoonnummer, string emailadres, decimal salaris, byte[] rowVersion)
        {
            Dierenarts dierenarts = new Dierenarts();
            dierenarts.Id = ID;
            dierenarts.Voornaam = voornaam;
            dierenarts.Achternaam = achternaam;
            dierenarts.Telefoonnummer = telefoonnummer;
            dierenarts.Emailadres = emailadres;
            dierenarts.Salaris = salaris;
            dierenarts.RowVersion = rowVersion;
            return dierenarts;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Voornaam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Voornaam
        {
            get
            {
                return this._Voornaam;
            }
            set
            {
                this.OnVoornaamChanging(value);
                if (object.Equals(this.Voornaam, value))
                {
                    return;
                }
                this._Voornaam = value;
                this.OnVoornaamChanged();
                this.OnPropertyChanged("Voornaam");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Voornaam;
        partial void OnVoornaamChanging(string value);
        partial void OnVoornaamChanged();
        /// <summary>
        /// There are no comments for Property Achternaam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Achternaam
        {
            get
            {
                return this._Achternaam;
            }
            set
            {
                this.OnAchternaamChanging(value);
                if (object.Equals(this.Achternaam, value))
                {
                    return;
                }
                this._Achternaam = value;
                this.OnAchternaamChanged();
                this.OnPropertyChanged("Achternaam");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Achternaam;
        partial void OnAchternaamChanging(string value);
        partial void OnAchternaamChanged();
        /// <summary>
        /// There are no comments for Property Telefoonnummer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Telefoonnummer
        {
            get
            {
                return this._Telefoonnummer;
            }
            set
            {
                this.OnTelefoonnummerChanging(value);
                if (object.Equals(this.Telefoonnummer, value))
                {
                    return;
                }
                this._Telefoonnummer = value;
                this.OnTelefoonnummerChanged();
                this.OnPropertyChanged("Telefoonnummer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Telefoonnummer;
        partial void OnTelefoonnummerChanging(string value);
        partial void OnTelefoonnummerChanged();
        /// <summary>
        /// There are no comments for Property Emailadres in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Emailadres
        {
            get
            {
                return this._Emailadres;
            }
            set
            {
                this.OnEmailadresChanging(value);
                if (object.Equals(this.Emailadres, value))
                {
                    return;
                }
                this._Emailadres = value;
                this.OnEmailadresChanged();
                this.OnPropertyChanged("Emailadres");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Emailadres;
        partial void OnEmailadresChanging(string value);
        partial void OnEmailadresChanged();
        /// <summary>
        /// There are no comments for Property Salaris in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Salaris
        {
            get
            {
                return this._Salaris;
            }
            set
            {
                this.OnSalarisChanging(value);
                if (object.Equals(this.Salaris, value))
                {
                    return;
                }
                this._Salaris = value;
                this.OnSalarisChanged();
                this.OnPropertyChanged("Salaris");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Salaris;
        partial void OnSalarisChanging(decimal value);
        partial void OnSalarisChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Behandelings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Behandeling> Behandelings
        {
            get
            {
                this.@__Behandelings.EnsureValueInitialized();
                return this._Behandelings;
            }
            set
            {
                this._Behandelings = value;
                this.OnPropertyChanged("Behandelings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Behandeling> _Behandelings = new global::System.Data.Services.Client.DataServiceCollection<Behandeling>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Dier in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Diers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Dier : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Dier object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="naam">Initial value of Naam.</param>
        /// <param name="gewicht">Initial value of Gewicht.</param>
        /// <param name="ras">Initial value of Ras.</param>
        /// <param name="dier_Eigenaar">Initial value of Dier_Eigenaar.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Dier CreateDier(int ID, string naam, decimal gewicht, string ras, int dier_Eigenaar, byte[] rowVersion)
        {
            Dier dier = new Dier();
            dier.Id = ID;
            dier.Naam = naam;
            dier.Gewicht = gewicht;
            dier.Ras = ras;
            dier.Dier_Eigenaar = dier_Eigenaar;
            dier.RowVersion = rowVersion;
            return dier;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Naam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Naam
        {
            get
            {
                return this._Naam;
            }
            set
            {
                this.OnNaamChanging(value);
                if (object.Equals(this.Naam, value))
                {
                    return;
                }
                this._Naam = value;
                this.OnNaamChanged();
                this.OnPropertyChanged("Naam");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Naam;
        partial void OnNaamChanging(string value);
        partial void OnNaamChanged();
        /// <summary>
        /// There are no comments for Property Soort in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Soort
        {
            get
            {
                return this._Soort;
            }
            set
            {
                this.OnSoortChanging(value);
                if (object.Equals(this.Soort, value))
                {
                    return;
                }
                this._Soort = value;
                this.OnSoortChanged();
                this.OnPropertyChanged("Soort");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Soort;
        partial void OnSoortChanging(string value);
        partial void OnSoortChanged();
        /// <summary>
        /// There are no comments for Property Gewicht in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Gewicht
        {
            get
            {
                return this._Gewicht;
            }
            set
            {
                this.OnGewichtChanging(value);
                if (object.Equals(this.Gewicht, value))
                {
                    return;
                }
                this._Gewicht = value;
                this.OnGewichtChanged();
                this.OnPropertyChanged("Gewicht");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Gewicht;
        partial void OnGewichtChanging(decimal value);
        partial void OnGewichtChanged();
        /// <summary>
        /// There are no comments for Property Ras in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ras
        {
            get
            {
                return this._Ras;
            }
            set
            {
                this.OnRasChanging(value);
                if (object.Equals(this.Ras, value))
                {
                    return;
                }
                this._Ras = value;
                this.OnRasChanged();
                this.OnPropertyChanged("Ras");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ras;
        partial void OnRasChanging(string value);
        partial void OnRasChanged();
        /// <summary>
        /// There are no comments for Property Geslacht in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Geslacht
        {
            get
            {
                return this._Geslacht;
            }
            set
            {
                this.OnGeslachtChanging(value);
                if (object.Equals(this.Geslacht, value))
                {
                    return;
                }
                this._Geslacht = value;
                this.OnGeslachtChanged();
                this.OnPropertyChanged("Geslacht");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Geslacht;
        partial void OnGeslachtChanging(string value);
        partial void OnGeslachtChanged();
        /// <summary>
        /// There are no comments for Property Geboortedatum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Geboortedatum
        {
            get
            {
                return this._Geboortedatum;
            }
            set
            {
                this.OnGeboortedatumChanging(value);
                if (object.Equals(this.Geboortedatum, value))
                {
                    return;
                }
                this._Geboortedatum = value;
                this.OnGeboortedatumChanged();
                this.OnPropertyChanged("Geboortedatum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Geboortedatum;
        partial void OnGeboortedatumChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnGeboortedatumChanged();
        /// <summary>
        /// There are no comments for Property Dier_Eigenaar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Dier_Eigenaar
        {
            get
            {
                return this._Dier_Eigenaar;
            }
            set
            {
                this.OnDier_EigenaarChanging(value);
                if (object.Equals(this.Dier_Eigenaar, value))
                {
                    return;
                }
                this._Dier_Eigenaar = value;
                this.OnDier_EigenaarChanged();
                this.OnPropertyChanged("Dier_Eigenaar");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Dier_Eigenaar;
        partial void OnDier_EigenaarChanging(int value);
        partial void OnDier_EigenaarChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Behandelings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Behandeling> Behandelings
        {
            get
            {
                this.@__Behandelings.EnsureValueInitialized();
                return this._Behandelings;
            }
            set
            {
                this._Behandelings = value;
                this.OnPropertyChanged("Behandelings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Behandeling> _Behandelings = new global::System.Data.Services.Client.DataServiceCollection<Behandeling>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Eigenaar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Eigenaar Eigenaar
        {
            get
            {
                this.@__Eigenaar.EnsureValueInitialized();
                return this._Eigenaar;
            }
            set
            {
                Eigenaar previous = this.Eigenaar;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Eigenaar = null;
                    this.@__Eigenaar.OnValueSet();
                    previous.Diers.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Dier_Eigenaar = value.Id;
                    }
                    else
                    {
                        this.Dier_Eigenaar = default(int);
                    }
                }
                this._Eigenaar = value;
                this.@__Eigenaar.OnValueSet();
                if ((value != null))
                {
                    value.@__Diers.Add(this);
                }
                this.___OnPropertyChanged("Eigenaar");
                this.OnPropertyChanged("Eigenaar");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Eigenaar _Eigenaar;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Eigenaar in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Eigenaars")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Eigenaar : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Eigenaar object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="naam">Initial value of Naam.</param>
        /// <param name="adres">Initial value of Adres.</param>
        /// <param name="postcode">Initial value of Postcode.</param>
        /// <param name="woonplaats">Initial value of Woonplaats.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Eigenaar CreateEigenaar(int ID, string naam, string adres, string postcode, string woonplaats, byte[] rowVersion)
        {
            Eigenaar eigenaar = new Eigenaar();
            eigenaar.Id = ID;
            eigenaar.Naam = naam;
            eigenaar.Adres = adres;
            eigenaar.Postcode = postcode;
            eigenaar.Woonplaats = woonplaats;
            eigenaar.RowVersion = rowVersion;
            return eigenaar;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Naam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Naam
        {
            get
            {
                return this._Naam;
            }
            set
            {
                this.OnNaamChanging(value);
                if (object.Equals(this.Naam, value))
                {
                    return;
                }
                this._Naam = value;
                this.OnNaamChanged();
                this.OnPropertyChanged("Naam");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Naam;
        partial void OnNaamChanging(string value);
        partial void OnNaamChanged();
        /// <summary>
        /// There are no comments for Property Adres in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Adres
        {
            get
            {
                return this._Adres;
            }
            set
            {
                this.OnAdresChanging(value);
                if (object.Equals(this.Adres, value))
                {
                    return;
                }
                this._Adres = value;
                this.OnAdresChanged();
                this.OnPropertyChanged("Adres");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Adres;
        partial void OnAdresChanging(string value);
        partial void OnAdresChanged();
        /// <summary>
        /// There are no comments for Property Postcode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Postcode
        {
            get
            {
                return this._Postcode;
            }
            set
            {
                this.OnPostcodeChanging(value);
                if (object.Equals(this.Postcode, value))
                {
                    return;
                }
                this._Postcode = value;
                this.OnPostcodeChanged();
                this.OnPropertyChanged("Postcode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Postcode;
        partial void OnPostcodeChanging(string value);
        partial void OnPostcodeChanged();
        /// <summary>
        /// There are no comments for Property Woonplaats in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Woonplaats
        {
            get
            {
                return this._Woonplaats;
            }
            set
            {
                this.OnWoonplaatsChanging(value);
                if (object.Equals(this.Woonplaats, value))
                {
                    return;
                }
                this._Woonplaats = value;
                this.OnWoonplaatsChanged();
                this.OnPropertyChanged("Woonplaats");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Woonplaats;
        partial void OnWoonplaatsChanging(string value);
        partial void OnWoonplaatsChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Diers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Dier> Diers
        {
            get
            {
                this.@__Diers.EnsureValueInitialized();
                return this._Diers;
            }
            set
            {
                this._Diers = value;
                this.OnPropertyChanged("Diers");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Dier> _Diers = new global::System.Data.Services.Client.DataServiceCollection<Dier>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Behandeling in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Behandelings")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Behandeling : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Behandeling object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="omschrijving">Initial value of Omschrijving.</param>
        /// <param name="behandeldatum">Initial value of Behandeldatum.</param>
        /// <param name="bedrag">Initial value of Bedrag.</param>
        /// <param name="behandeling_Dier">Initial value of Behandeling_Dier.</param>
        /// <param name="behandeling_Dierenarts">Initial value of Behandeling_Dierenarts.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Behandeling CreateBehandeling(int ID, string omschrijving, global::System.DateTime behandeldatum, decimal bedrag, int behandeling_Dier, int behandeling_Dierenarts, byte[] rowVersion)
        {
            Behandeling behandeling = new Behandeling();
            behandeling.Id = ID;
            behandeling.Omschrijving = omschrijving;
            behandeling.Behandeldatum = behandeldatum;
            behandeling.Bedrag = bedrag;
            behandeling.Behandeling_Dier = behandeling_Dier;
            behandeling.Behandeling_Dierenarts = behandeling_Dierenarts;
            behandeling.RowVersion = rowVersion;
            return behandeling;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Omschrijving in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Omschrijving
        {
            get
            {
                return this._Omschrijving;
            }
            set
            {
                this.OnOmschrijvingChanging(value);
                if (object.Equals(this.Omschrijving, value))
                {
                    return;
                }
                this._Omschrijving = value;
                this.OnOmschrijvingChanged();
                this.OnPropertyChanged("Omschrijving");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Omschrijving;
        partial void OnOmschrijvingChanging(string value);
        partial void OnOmschrijvingChanged();
        /// <summary>
        /// There are no comments for Property Behandeldatum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Behandeldatum
        {
            get
            {
                return this._Behandeldatum;
            }
            set
            {
                this.OnBehandeldatumChanging(value);
                if (object.Equals(this.Behandeldatum, value))
                {
                    return;
                }
                this._Behandeldatum = value;
                this.OnBehandeldatumChanged();
                this.OnPropertyChanged("Behandeldatum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Behandeldatum;
        partial void OnBehandeldatumChanging(global::System.DateTime value);
        partial void OnBehandeldatumChanged();
        /// <summary>
        /// There are no comments for Property Bedrag in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Bedrag
        {
            get
            {
                return this._Bedrag;
            }
            set
            {
                this.OnBedragChanging(value);
                if (object.Equals(this.Bedrag, value))
                {
                    return;
                }
                this._Bedrag = value;
                this.OnBedragChanged();
                this.OnPropertyChanged("Bedrag");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Bedrag;
        partial void OnBedragChanging(decimal value);
        partial void OnBedragChanged();
        /// <summary>
        /// There are no comments for Property Behandeling_Dier in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Behandeling_Dier
        {
            get
            {
                return this._Behandeling_Dier;
            }
            set
            {
                this.OnBehandeling_DierChanging(value);
                if (object.Equals(this.Behandeling_Dier, value))
                {
                    return;
                }
                this._Behandeling_Dier = value;
                this.OnBehandeling_DierChanged();
                this.OnPropertyChanged("Behandeling_Dier");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Behandeling_Dier;
        partial void OnBehandeling_DierChanging(int value);
        partial void OnBehandeling_DierChanged();
        /// <summary>
        /// There are no comments for Property Behandeling_Dierenarts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Behandeling_Dierenarts
        {
            get
            {
                return this._Behandeling_Dierenarts;
            }
            set
            {
                this.OnBehandeling_DierenartsChanging(value);
                if (object.Equals(this.Behandeling_Dierenarts, value))
                {
                    return;
                }
                this._Behandeling_Dierenarts = value;
                this.OnBehandeling_DierenartsChanged();
                this.OnPropertyChanged("Behandeling_Dierenarts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Behandeling_Dierenarts;
        partial void OnBehandeling_DierenartsChanging(int value);
        partial void OnBehandeling_DierenartsChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Dier in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Dier Dier
        {
            get
            {
                this.@__Dier.EnsureValueInitialized();
                return this._Dier;
            }
            set
            {
                Dier previous = this.Dier;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Dier = null;
                    this.@__Dier.OnValueSet();
                    previous.Behandelings.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Behandeling_Dier = value.Id;
                    }
                    else
                    {
                        this.Behandeling_Dier = default(int);
                    }
                }
                this._Dier = value;
                this.@__Dier.OnValueSet();
                if ((value != null))
                {
                    value.@__Behandelings.Add(this);
                }
                this.___OnPropertyChanged("Dier");
                this.OnPropertyChanged("Dier");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Dier _Dier;
        /// <summary>
        /// There are no comments for Dierenarts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Dierenarts Dierenarts
        {
            get
            {
                this.@__Dierenarts.EnsureValueInitialized();
                return this._Dierenarts;
            }
            set
            {
                Dierenarts previous = this.Dierenarts;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Dierenarts = null;
                    this.@__Dierenarts.OnValueSet();
                    previous.Behandelings.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Behandeling_Dierenarts = value.Id;
                    }
                    else
                    {
                        this.Behandeling_Dierenarts = default(int);
                    }
                }
                this._Dierenarts = value;
                this.@__Dierenarts.OnValueSet();
                if ((value != null))
                {
                    value.@__Behandelings.Add(this);
                }
                this.___OnPropertyChanged("Dierenarts");
                this.OnPropertyChanged("Dierenarts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Dierenarts _Dierenarts;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
