

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class Dierenarts : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Dierenarts entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Dierenarts()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Dierenarts(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Dierenarts> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Dierenarts.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Dierenarts_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Dierenarts_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Dierenarts.DetailsClass.SetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Voornaam
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Voornaam);
            }
            set
            {
                global::LightSwitchApplication.Dierenarts.DetailsClass.SetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Voornaam, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Voornaam_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Voornaam_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Voornaam_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Achternaam
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Achternaam);
            }
            set
            {
                global::LightSwitchApplication.Dierenarts.DetailsClass.SetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Achternaam, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Achternaam_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Achternaam_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Achternaam_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Telefoonnummer
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Telefoonnummer);
            }
            set
            {
                global::LightSwitchApplication.Dierenarts.DetailsClass.SetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Telefoonnummer, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefoonnummer_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefoonnummer_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Telefoonnummer_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Emailadres
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Emailadres);
            }
            set
            {
                global::LightSwitchApplication.Dierenarts.DetailsClass.SetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Emailadres, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Emailadres_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Emailadres_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Emailadres_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Salaris
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Salaris);
            }
            set
            {
                global::LightSwitchApplication.Dierenarts.DetailsClass.SetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Salaris, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Salaris_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Salaris_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Salaris_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Dierenarts.DetailsClass.SetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int AantalBehandelingen
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.AantalBehandelingen);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AantalBehandelingen_Compute(ref int result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AantalBehandelingen_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Behandeling> Behandelings
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetValue(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Behandelings);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Behandeling> BehandelingsQuery
        {
            get
            {
                return global::LightSwitchApplication.Dierenarts.DetailsClass.GetQuery(this, global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Behandelings);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Dierenarts,
                global::LightSwitchApplication.Dierenarts.DetailsClass,
                global::LightSwitchApplication.Dierenarts.DetailsClass.IImplementation,
                global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass>.Entry
                __DierenartsEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass>.Entry(
                    global::LightSwitchApplication.Dierenarts.DetailsClass.__Dierenarts_CreateNew,
                    global::LightSwitchApplication.Dierenarts.DetailsClass.__Dierenarts_Created,
                    global::LightSwitchApplication.Dierenarts.DetailsClass.__Dierenarts_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Dierenarts __Dierenarts_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Dierenarts> es)
            {
                return new global::LightSwitchApplication.Dierenarts(es);
            }
            private static void __Dierenarts_Created(global::LightSwitchApplication.Dierenarts e)
            {
                e.Dierenarts_Created();
            }
            private static bool __Dierenarts_AllowSaveWithErrors(global::LightSwitchApplication.Dierenarts e)
            {
                bool result = false;
                e.Dierenarts_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string> Voornaam
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Voornaam) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string> Achternaam
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Achternaam) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string> Telefoonnummer
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Telefoonnummer) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string> Emailadres
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Emailadres) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, decimal> Salaris
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Salaris) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int> AantalBehandelingen
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.AantalBehandelingen) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::LightSwitchApplication.Behandeling> Behandelings
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Behandelings) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::LightSwitchApplication.Behandeling>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Voornaam { get; set; }
                new string Achternaam { get; set; }
                new string Telefoonnummer { get; set; }
                new string Emailadres { get; set; }
                new decimal Salaris { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable Behandelings { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Dierenarts e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Dierenarts e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry
                    Voornaam = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry(
                        "Voornaam",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Voornaam_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Voornaam_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Voornaam_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Voornaam_GetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Voornaam_SetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Voornaam_OnValueChanged);
                private static void _Voornaam_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._Voornaam, sf);
                }
                private static bool _Voornaam_ComputeIsReadOnly(global::LightSwitchApplication.Dierenarts e)
                {
                    bool result = false;
                    e.Voornaam_IsReadOnly(ref result);
                    return result;
                }
                private static void _Voornaam_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Voornaam_Validate(r);
                }
                private static string _Voornaam_GetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.Voornaam;
                }
                private static void _Voornaam_SetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Voornaam = v;
                }
                private static void _Voornaam_OnValueChanged(global::LightSwitchApplication.Dierenarts e)
                {
                    e.Voornaam_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry
                    Achternaam = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry(
                        "Achternaam",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Achternaam_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Achternaam_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Achternaam_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Achternaam_GetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Achternaam_SetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Achternaam_OnValueChanged);
                private static void _Achternaam_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._Achternaam, sf);
                }
                private static bool _Achternaam_ComputeIsReadOnly(global::LightSwitchApplication.Dierenarts e)
                {
                    bool result = false;
                    e.Achternaam_IsReadOnly(ref result);
                    return result;
                }
                private static void _Achternaam_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Achternaam_Validate(r);
                }
                private static string _Achternaam_GetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.Achternaam;
                }
                private static void _Achternaam_SetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Achternaam = v;
                }
                private static void _Achternaam_OnValueChanged(global::LightSwitchApplication.Dierenarts e)
                {
                    e.Achternaam_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry
                    Telefoonnummer = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry(
                        "Telefoonnummer",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Telefoonnummer_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Telefoonnummer_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Telefoonnummer_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Telefoonnummer_GetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Telefoonnummer_SetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Telefoonnummer_OnValueChanged);
                private static void _Telefoonnummer_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._Telefoonnummer, sf);
                }
                private static bool _Telefoonnummer_ComputeIsReadOnly(global::LightSwitchApplication.Dierenarts e)
                {
                    bool result = false;
                    e.Telefoonnummer_IsReadOnly(ref result);
                    return result;
                }
                private static void _Telefoonnummer_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Telefoonnummer_Validate(r);
                }
                private static string _Telefoonnummer_GetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.Telefoonnummer;
                }
                private static void _Telefoonnummer_SetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Telefoonnummer = v;
                }
                private static void _Telefoonnummer_OnValueChanged(global::LightSwitchApplication.Dierenarts e)
                {
                    e.Telefoonnummer_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry
                    Emailadres = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry(
                        "Emailadres",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Emailadres_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Emailadres_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Emailadres_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Emailadres_GetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Emailadres_SetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Emailadres_OnValueChanged);
                private static void _Emailadres_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._Emailadres, sf);
                }
                private static bool _Emailadres_ComputeIsReadOnly(global::LightSwitchApplication.Dierenarts e)
                {
                    bool result = false;
                    e.Emailadres_IsReadOnly(ref result);
                    return result;
                }
                private static void _Emailadres_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Emailadres_Validate(r);
                }
                private static string _Emailadres_GetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.Emailadres;
                }
                private static void _Emailadres_SetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Emailadres = v;
                }
                private static void _Emailadres_OnValueChanged(global::LightSwitchApplication.Dierenarts e)
                {
                    e.Emailadres_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, decimal>.Entry
                    Salaris = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, decimal>.Entry(
                        "Salaris",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Salaris_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Salaris_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Salaris_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Salaris_GetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Salaris_SetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Salaris_OnValueChanged);
                private static void _Salaris_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._Salaris, sf);
                }
                private static bool _Salaris_ComputeIsReadOnly(global::LightSwitchApplication.Dierenarts e)
                {
                    bool result = false;
                    e.Salaris_IsReadOnly(ref result);
                    return result;
                }
                private static void _Salaris_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Salaris_Validate(r);
                }
                private static decimal _Salaris_GetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.Salaris;
                }
                private static void _Salaris_SetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.Salaris = v;
                }
                private static void _Salaris_OnValueChanged(global::LightSwitchApplication.Dierenarts e)
                {
                    e.Salaris_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Dierenarts e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.Dierenarts e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.Dierenarts e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.Dierenarts e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.Dierenarts e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.Dierenarts e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.Dierenarts e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.Dierenarts e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Dierenarts e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Dierenarts.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Dierenarts e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int>.Entry
                    AantalBehandelingen = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int>.Entry(
                        "AantalBehandelingen",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._AantalBehandelingen_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._AantalBehandelingen_Validate,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._AantalBehandelingen_ComputeValue);
                private static void _AantalBehandelingen_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._AantalBehandelingen, sf);
                }
                private static void _AantalBehandelingen_Validate(global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.AantalBehandelingen_Validate(r);
                }
                private static int _AantalBehandelingen_ComputeValue(global::LightSwitchApplication.Dierenarts e)
                {
                    int value = default(int);
                    e.AantalBehandelingen_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::LightSwitchApplication.Behandeling>.Entry
                    Behandelings = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::LightSwitchApplication.Behandeling>.Entry(
                        "Behandelings",
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Behandelings_Stub,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Behandelings_GetReferencedEntities,
                        global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties._Behandelings_GetEntityCollection);
                private static void _Behandelings_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Dierenarts.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::LightSwitchApplication.Behandeling>.Data> c, global::LightSwitchApplication.Dierenarts.DetailsClass d, object sf)
                {
                    c(d, ref d._Behandelings, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Behandeling> _Behandelings_GetReferencedEntities(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Behandeling, global::LightSwitchApplication.Behandeling.DetailsClass>(global::LightSwitchApplication.Dierenarts.DetailsClass.PropertySetProperties.Behandelings, ref d._Behandelings);
                }
                private static global::System.Collections.IEnumerable _Behandelings_GetEntityCollection(global::LightSwitchApplication.Dierenarts.DetailsClass d)
                {
                    return d.ImplementationEntity.Behandelings;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data _Voornaam;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data _Achternaam;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data _Telefoonnummer;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data _Emailadres;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, decimal>.Data _Salaris;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, int>.Data _AantalBehandelingen;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Dierenarts, global::LightSwitchApplication.Dierenarts.DetailsClass, global::LightSwitchApplication.Behandeling>.Data _Behandelings;
            
        }
    
        #endregion
    }
    
    #endregion
}
