//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_Inserting(global::LightSwitchApplication.Dierenarts entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_Inserted(global::LightSwitchApplication.Dierenarts entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_Updating(global::LightSwitchApplication.Dierenarts entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_Updated(global::LightSwitchApplication.Dierenarts entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_Deleting(global::LightSwitchApplication.Dierenarts entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_Deleted(global::LightSwitchApplication.Dierenarts entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_Validate(global::LightSwitchApplication.Dierenarts entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Dierenarts, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_Inserting(global::LightSwitchApplication.Dier entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_Inserted(global::LightSwitchApplication.Dier entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_Updating(global::LightSwitchApplication.Dier entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_Updated(global::LightSwitchApplication.Dier entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_Deleting(global::LightSwitchApplication.Dier entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_Deleted(global::LightSwitchApplication.Dier entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_Validate(global::LightSwitchApplication.Dier entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Diers_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Dier, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_Inserting(global::LightSwitchApplication.Eigenaar entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_Inserted(global::LightSwitchApplication.Eigenaar entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_Updating(global::LightSwitchApplication.Eigenaar entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_Updated(global::LightSwitchApplication.Eigenaar entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_Deleting(global::LightSwitchApplication.Eigenaar entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_Deleted(global::LightSwitchApplication.Eigenaar entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_Validate(global::LightSwitchApplication.Eigenaar entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Eigenaars_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Eigenaar, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_Inserting(global::LightSwitchApplication.Behandeling entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_Inserted(global::LightSwitchApplication.Behandeling entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_Updating(global::LightSwitchApplication.Behandeling entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_Updated(global::LightSwitchApplication.Behandeling entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_Deleting(global::LightSwitchApplication.Behandeling entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_Deleted(global::LightSwitchApplication.Behandeling entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_Validate(global::LightSwitchApplication.Behandeling entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Behandelings_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Behandeling, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EigenarenUitBreda_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void EigenarenUitBreda_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EigenarenUitBreda_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.Eigenaar> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void EigenarenUitBreda_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Eigenaar> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void EigenarenUitBreda_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EigenarenOpInput_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void EigenarenOpInput_Executing(string Woonplaats);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EigenarenOpInput_PreprocessQuery(string Woonplaats, ref global::System.Linq.IQueryable<global::LightSwitchApplication.Eigenaar> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void EigenarenOpInput_Executed(string Woonplaats, global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Eigenaar> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void EigenarenOpInput_ExecuteFailed(string Woonplaats, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AlleKattenEnHonden_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void AlleKattenEnHonden_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AlleKattenEnHonden_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.Dier> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void AlleKattenEnHonden_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Dier> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void AlleKattenEnHonden_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MeerDanTienDieren_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MeerDanTienDieren_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MeerDanTienDieren_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.Dierenarts> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MeerDanTienDieren_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Dierenarts> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MeerDanTienDieren_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsenBijAantalBehandelingenInput_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void DierenartsenBijAantalBehandelingenInput_Executing(global::System.Nullable<int> AantalBehandelingenParameter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DierenartsenBijAantalBehandelingenInput_PreprocessQuery(global::System.Nullable<int> AantalBehandelingenParameter, ref global::System.Linq.IQueryable<global::LightSwitchApplication.Dierenarts> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void DierenartsenBijAantalBehandelingenInput_Executed(global::System.Nullable<int> AantalBehandelingenParameter, global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Dierenarts> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void DierenartsenBijAantalBehandelingenInput_ExecuteFailed(global::System.Nullable<int> AantalBehandelingenParameter, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationData_InitializingConnection(global::Microsoft.LightSwitch.DatabaseConnectionState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Dierenarts>
                __DierenartsSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Dierenarts>(
                    "DierenartsSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsSet_Filter);
            private static bool __DierenartsSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.DierenartsSet_CanInsert(ref result);
                return result;
            }
            private static bool __DierenartsSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.DierenartsSet_CanUpdate(ref result);
                return result;
            }
            private static bool __DierenartsSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.DierenartsSet_CanDelete(ref result);
                return result;
            }
            private static bool __DierenartsSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.DierenartsSet_CanRead(ref result);
                return result;
            }
            private static void __DierenartsSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dierenarts e)
            {
                d.DierenartsSet_Inserting(e);
            }
            private static void __DierenartsSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dierenarts e)
            {
                d.DierenartsSet_Inserted(e);
            }
            private static void __DierenartsSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dierenarts e)
            {
                d.DierenartsSet_Updating(e);
            }
            private static void __DierenartsSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dierenarts e)
            {
                d.DierenartsSet_Updated(e);
            }
            private static void __DierenartsSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dierenarts e)
            {
                d.DierenartsSet_Deleting(e);
            }
            private static void __DierenartsSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dierenarts e)
            {
                d.DierenartsSet_Deleted(e);
            }
            private static void __DierenartsSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dierenarts e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.DierenartsSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Dierenarts, bool>> __DierenartsSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Dierenarts, bool>> filter = null;
                d.DierenartsSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Dier>
                __DiersEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Dier>(
                    "Diers",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Diers_Filter);
            private static bool __Diers_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Diers_CanInsert(ref result);
                return result;
            }
            private static bool __Diers_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Diers_CanUpdate(ref result);
                return result;
            }
            private static bool __Diers_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Diers_CanDelete(ref result);
                return result;
            }
            private static bool __Diers_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Diers_CanRead(ref result);
                return result;
            }
            private static void __Diers_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dier e)
            {
                d.Diers_Inserting(e);
            }
            private static void __Diers_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dier e)
            {
                d.Diers_Inserted(e);
            }
            private static void __Diers_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dier e)
            {
                d.Diers_Updating(e);
            }
            private static void __Diers_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dier e)
            {
                d.Diers_Updated(e);
            }
            private static void __Diers_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dier e)
            {
                d.Diers_Deleting(e);
            }
            private static void __Diers_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dier e)
            {
                d.Diers_Deleted(e);
            }
            private static void __Diers_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Dier e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Diers_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Dier, bool>> __Diers_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Dier, bool>> filter = null;
                d.Diers_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Eigenaar>
                __EigenaarsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Eigenaar>(
                    "Eigenaars",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Eigenaars_Filter);
            private static bool __Eigenaars_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Eigenaars_CanInsert(ref result);
                return result;
            }
            private static bool __Eigenaars_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Eigenaars_CanUpdate(ref result);
                return result;
            }
            private static bool __Eigenaars_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Eigenaars_CanDelete(ref result);
                return result;
            }
            private static bool __Eigenaars_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Eigenaars_CanRead(ref result);
                return result;
            }
            private static void __Eigenaars_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Eigenaar e)
            {
                d.Eigenaars_Inserting(e);
            }
            private static void __Eigenaars_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Eigenaar e)
            {
                d.Eigenaars_Inserted(e);
            }
            private static void __Eigenaars_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Eigenaar e)
            {
                d.Eigenaars_Updating(e);
            }
            private static void __Eigenaars_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Eigenaar e)
            {
                d.Eigenaars_Updated(e);
            }
            private static void __Eigenaars_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Eigenaar e)
            {
                d.Eigenaars_Deleting(e);
            }
            private static void __Eigenaars_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Eigenaar e)
            {
                d.Eigenaars_Deleted(e);
            }
            private static void __Eigenaars_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Eigenaar e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Eigenaars_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Eigenaar, bool>> __Eigenaars_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Eigenaar, bool>> filter = null;
                d.Eigenaars_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Behandeling>
                __BehandelingsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Behandeling>(
                    "Behandelings",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Behandelings_Filter);
            private static bool __Behandelings_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Behandelings_CanInsert(ref result);
                return result;
            }
            private static bool __Behandelings_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Behandelings_CanUpdate(ref result);
                return result;
            }
            private static bool __Behandelings_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Behandelings_CanDelete(ref result);
                return result;
            }
            private static bool __Behandelings_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Behandelings_CanRead(ref result);
                return result;
            }
            private static void __Behandelings_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Behandeling e)
            {
                d.Behandelings_Inserting(e);
            }
            private static void __Behandelings_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Behandeling e)
            {
                d.Behandelings_Inserted(e);
            }
            private static void __Behandelings_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Behandeling e)
            {
                d.Behandelings_Updating(e);
            }
            private static void __Behandelings_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Behandeling e)
            {
                d.Behandelings_Updated(e);
            }
            private static void __Behandelings_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Behandeling e)
            {
                d.Behandelings_Deleting(e);
            }
            private static void __Behandelings_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Behandeling e)
            {
                d.Behandelings_Deleted(e);
            }
            private static void __Behandelings_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Behandeling e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Behandelings_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Behandeling, bool>> __Behandelings_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Behandeling, bool>> filter = null;
                d.Behandelings_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Eigenaar>
                __EigenarenUitBredaEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Eigenaar>(
                    "EigenarenUitBreda",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EigenarenUitBreda_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EigenarenUitBreda_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EigenarenUitBreda_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EigenarenUitBreda_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EigenarenUitBreda_PreprocessQuery);
            private static bool __EigenarenUitBreda_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.EigenarenUitBreda_CanExecute(ref r);
                return r;
            }
            private static void __EigenarenUitBreda_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.EigenarenUitBreda_Executing();
            }
            private static void __EigenarenUitBreda_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.EigenarenUitBreda_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Eigenaar>)args[0]);
            }
            private static void __EigenarenUitBreda_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.EigenarenUitBreda_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __EigenarenUitBreda_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Eigenaar> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Eigenaar>)args[0];
                d.EigenarenUitBreda_PreprocessQuery(ref query);
                return query;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Eigenaar>
                __EigenarenOpInputEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Eigenaar>(
                    "EigenarenOpInput",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EigenarenOpInput_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EigenarenOpInput_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EigenarenOpInput_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EigenarenOpInput_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__EigenarenOpInput_PreprocessQuery);
            private static bool __EigenarenOpInput_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.EigenarenOpInput_CanExecute(ref r);
                return r;
            }
            private static void __EigenarenOpInput_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.EigenarenOpInput_Executing((string)args[0]);
            }
            private static void __EigenarenOpInput_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.EigenarenOpInput_Executed((string)args[0], (global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Eigenaar>)args[1]);
            }
            private static void __EigenarenOpInput_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.EigenarenOpInput_ExecuteFailed((string)args[0], ex);
            }
            private static global::System.Linq.IQueryable __EigenarenOpInput_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Eigenaar> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Eigenaar>)args[1];
                d.EigenarenOpInput_PreprocessQuery((string)args[0], ref query);
                return query;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Dier>
                __AlleKattenEnHondenEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Dier>(
                    "AlleKattenEnHonden",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AlleKattenEnHonden_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AlleKattenEnHonden_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AlleKattenEnHonden_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AlleKattenEnHonden_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AlleKattenEnHonden_PreprocessQuery);
            private static bool __AlleKattenEnHonden_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.AlleKattenEnHonden_CanExecute(ref r);
                return r;
            }
            private static void __AlleKattenEnHonden_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.AlleKattenEnHonden_Executing();
            }
            private static void __AlleKattenEnHonden_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.AlleKattenEnHonden_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Dier>)args[0]);
            }
            private static void __AlleKattenEnHonden_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.AlleKattenEnHonden_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __AlleKattenEnHonden_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Dier> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Dier>)args[0];
                d.AlleKattenEnHonden_PreprocessQuery(ref query);
                return query;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Dierenarts>
                __MeerDanTienDierenEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Dierenarts>(
                    "MeerDanTienDieren",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MeerDanTienDieren_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MeerDanTienDieren_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MeerDanTienDieren_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MeerDanTienDieren_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MeerDanTienDieren_PreprocessQuery);
            private static bool __MeerDanTienDieren_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.MeerDanTienDieren_CanExecute(ref r);
                return r;
            }
            private static void __MeerDanTienDieren_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.MeerDanTienDieren_Executing();
            }
            private static void __MeerDanTienDieren_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.MeerDanTienDieren_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Dierenarts>)args[0]);
            }
            private static void __MeerDanTienDieren_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.MeerDanTienDieren_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __MeerDanTienDieren_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Dierenarts> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Dierenarts>)args[0];
                d.MeerDanTienDieren_PreprocessQuery(ref query);
                return query;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Dierenarts>
                __DierenartsenBijAantalBehandelingenInputEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Dierenarts>(
                    "DierenartsenBijAantalBehandelingenInput",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsenBijAantalBehandelingenInput_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsenBijAantalBehandelingenInput_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsenBijAantalBehandelingenInput_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsenBijAantalBehandelingenInput_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__DierenartsenBijAantalBehandelingenInput_PreprocessQuery);
            private static bool __DierenartsenBijAantalBehandelingenInput_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.DierenartsenBijAantalBehandelingenInput_CanExecute(ref r);
                return r;
            }
            private static void __DierenartsenBijAantalBehandelingenInput_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.DierenartsenBijAantalBehandelingenInput_Executing((global::System.Nullable<int>)args[0]);
            }
            private static void __DierenartsenBijAantalBehandelingenInput_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.DierenartsenBijAantalBehandelingenInput_Executed((global::System.Nullable<int>)args[0], (global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Dierenarts>)args[1]);
            }
            private static void __DierenartsenBijAantalBehandelingenInput_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.DierenartsenBijAantalBehandelingenInput_ExecuteFailed((global::System.Nullable<int>)args[0], ex);
            }
            private static global::System.Linq.IQueryable __DierenartsenBijAantalBehandelingenInput_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Dierenarts> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Dierenarts>)args[1];
                d.DierenartsenBijAantalBehandelingenInput_PreprocessQuery((global::System.Nullable<int>)args[0], ref query);
                return query;
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>
                ___DatabaseAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ApplicationData_InitializingConnection);
            private static void __ApplicationData_InitializingConnection(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.DatabaseConnectionState state)
            {
                d.ApplicationData_InitializingConnection(state);
            }
        }
    
        #endregion
    }
    
    #endregion
}
